name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/chekout@v3

      - name: Setup Node.js
        uses: actions/setup-npde@v3
        with:
          node-version: 16

      - run: npm ci

      - Build Storybook
        run: npm run build-storybook

      - name: Deploy Storybook
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}